### ISSUE TITLE
CRUD (Create, read, update, delete) add recurring absences

### ISSUE THREAD

**Issue by pzach** [rropen/absense-planner#42]

**Comment by Jai-Rai** [comment]
May include weekends/work week

**Comment by diarmuidclarke** [comment]
@J-Wheeler849277  @Jai-Rai  - Hi Guys, 
I notice in my browser F12 (developer) view, i get errors when i click "add rule" for recurring absence.
maybe soemthing wrong in my environment? welcome any advice you can give me, thanks!

﻿
recurrence-widget.js:1118 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at recurrence.widget.RuleYearlyForm.init_dom (recurrence-widget.js:1118:65)
    at recurrence.widget.RuleYearlyForm.init (recurrence-widget.js:1104:14)
    at new recurrence.widget.RuleYearlyForm (recurrence-widget.js:1097:10)
    at recurrence.widget.RuleForm.<anonymous> (recurrence-widget.js:957:25)
    at recurrence.js:906:25
    at Object.foreach (recurrence.js:877:32)
    at recurrence.widget.RuleForm.init_dom (recurrence-widget.js:954:43)
    at recurrence.widget.RuleForm.init (recurrence-widget.js:728:14)
    at new recurrence.widget.RuleForm (recurrence-widget.js:706:10)
    at recurrence.widget.Widget.add_rule_panel (recurrence-widget.js:529:20)
